### ISSUE TITLE
Installation Code isnt working?

### ISSUE THREAD

**Issue by DocHollidayTV** [Synse/dclone-discord#10]
So im installing the bot on my discord server and every time i put in the install code into Python it doesnt work. just says

**Comment by DocHollidayTV** [comment]
>>> pip3 install -r requirements.txt
  File "<stdin>", line 1
    pip3 install -r requirements.txt
         ^^^^^^^
SyntaxError: invalid syntax
>>>
>>> git clone https://github.com/Synse/dclone-discord.git
  File "<stdin>", line 1
    git clone https://github.com/Synse/dclone-discord.git
        ^^^^^
SyntaxError: invalid syntax
>>> cd dclone-discord
  File "<stdin>", line 1
    cd dclone-discord
       ^^^^^^
SyntaxError: invalid syntax
>>> git clone https://github.com/Synse/dclone-discord.git
  File "<stdin>", line 1
    git clone https://github.com/Synse/dclone-discord.git
        ^^^^^
SyntaxError: invalid syntax
>>> cd dclone-discord
  File "<stdin>", line 1
    cd dclone-discord
       ^^^^^^
SyntaxError: invalid syntax
>>> pip3 install -r requirements.txt

**Comment by DocHollidayTV** [comment]
> > So im installing the bot on my discord server and every time i put in the install code into Python it doesnt work. just says
> 
> Hey @DocHollidayTV the installation code doesn't go into Python, you run each of the listed commands from your Terminal/Command Prompt. The commands listed will work on most macOS/Linux systems without any additional effort and should work on Windows but you'd need to install Python and Git before running them.
> 
> Can you tell me a bit more about your setup: Are you on Windows, Linux, or macOS?

Thank you for the reply, as you can probably assume i know very little about this type of program in particular.

I am Running Windows 10 Pro on my computer. I have installed the latest python and will install GIT and try the cmd prmt way.

Anything else i may need to know such as downloading or creating a file with the code saved somewhere?

**Comment by Synse** [comment]
> Anything else i may need to know such as downloading or creating a file with the code saved somewhere?

No, the `git clone https://github.com/Synse/dclone-discord.git` command will copy all of the files from this repository locally including the [`requirements.txt`](https://raw.githubusercontent.com/Synse/dclone-discord/main/requirements.txt) and [`dclone_discord.py`](https://raw.githubusercontent.com/Synse/dclone-discord/main/dclone_discord.py) file that you need to run the bot.

You could also skip installing git and running the `git clone https://github.com/Synse/dclone-discord.git` by downloading those two files and saving them to your local system. I would recommend using git though because you can update the bot in the future by just running [`git pull`](https://github.com/git-guides/git-pull) in the folder you cloned the repo into.

---

That said, please do keep in mind that I haven't tested the bot from Windows so it may not even work. Since your on Windows you'll probably need to add `.exe` to the `git`, `pip3`, and `python3` commands:

```sh
git.exe clone https://github.com/Synse/dclone-discord.git
cd dclone-discord
pip3.exe install -r requirements.txt
```

and after [setting the environment variables](https://www.google.com/search?q=windows+10+set+environment+variable), run the bot with `python3.exe dclone_discord.py`. But I've never used git or python on Windows so I could be wrong here.
